package com.unitekndt.mqnavigator.entity;

public enum Location {
    FIRST_GATE,
    LAST_GATE,
    PREVIOUS_GATE_BASED_ON_SELECTED,
    LATEST_GATE_BASED_ON_SELECTED,
    NEXT_GATE_BASED_ON_SELECTED,
    PREVIOUS_GATE_BASED_ON_CURRENT,
    LATEST_GATE_BASED_ON_CURRENT,
    NEXT_GATE_BASED_ON_CURRENT,
}